### ISSUE TITLE
Unhandled promise error

### ISSUE THREAD

**Issue by zpallin** [YYZ-Engine/yyz-engine#28]
I let my docker image run too long and it exposed an interesting error. Please see if you can find the issue. If you can write a test for it, too, that would be cool, but only if it's not too complicated (such as making sure the code does not have an unhandled promise).

```
zpallin@ZPALLIN-X1:yyz-engine (git:ychoy/issue_17)$ sudo docker run yyz_hello_world

> hello-world-client@1.0.0 dev /usr/src/app
> concurrently --kill-others-on-fail "npm run server" "npm run client"

[0] 
[0] > hello-world-client@1.0.0 server /usr/src/app
[0] > nodemon server.js
[0] 
[1] 
[1] > hello-world-client@1.0.0 client /usr/src/app
[1] > cd client && npm install && npm start
[1] 
[0] [nodemon] 1.17.5
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching: *.*
[0] [nodemon] starting `node server.js`
[1] npm WARN notice [SECURITY] url-parse has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=url-parse&version=1.4.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
^C^C


^C^C^C[1] 
[1] > uglifyjs-webpack-plugin@0.4.6 postinstall /usr/src/app/client/node_modules/uglifyjs-webpack-plugin
[1] > node lib/post_install.js
[1] 
[1] npm WARN hello-world-client@0.1.0 No description
[1] npm WARN hello-world-client@0.1.0 No repository field.
[1] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
[1] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[1] 
[1] added 1550 packages in 19.219s
[1] 
[1] > hello-world-client@0.1.0 start /usr/src/app/client
[1] > react-scripts start
[1] 
[1] Starting the development server...
[1] 
[1] Compiled successfully!
[1] 
[1] You can now view hello-world-client in the browser.
[1] 
[1]   Local:            http://localhost:3000/
[1]   On Your Network:  http://172.17.0.2:3000/
[1] 
[1] Note that the development build is not optimized.
[1] To create a production build, use npm run build.
[1] 
^[[6;7~[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[0] (node:70) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[1] Proxy error: Could not proxy request /api/world?json from 172.17.0.2:3000 to http://localhost:5000/.
[1] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
[1] 
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
[0] (node:70) UnhandledPromiseRejectionWarning: Error: Query timed out
[0]     at DNS._ontimeout (/usr/src/app/node_modules/dns-socket/index.js:99:18)
[0]     at Timeout.ontimeout (/usr/src/app/node_modules/dns-socket/index.js:53:10)
[0]     at ontimeout (timers.js:498:11)
[0]     at tryOnTimeout (timers.js:323:5)
[0]     at Timer.listOnTimeout (timers.js:290:5)
[0] (node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2
```

**Comment by ychoy** [comment]
@zpallin  Can you make this an issue in https://github.com/YYZ-Engine/hello-world/issues?
